'use client';

import { useState } from 'react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';

const data = {
  pt: { kicker: 'Sobre a HortiVita', title: 'Uma ideia simples que cresceu em família.', lead: 'A HortiVita nasceu para facilitar o cultivo em lugares com pouco espaço e aproximar as pessoas da origem dos alimentos.', section: 'Nossa origem', headline: 'Cultivar bem também pode ser prático.', body: 'O projeto reúne experiência prática, criatividade e conhecimento agronômico. A solução foi sendo construída e melhorada em família, sempre com um objetivo claro: aproveitar melhor o espaço, manter as plantas por perto e tornar o cuidado mais confortável.', historyTitle: 'Da necessidade real para uma horta que gira.', history: ['A ideia começou com a busca por uma forma de cultivar em locais onde não há espaço para canteiros. As plantas foram organizadas em prateleiras ao redor de um eixo, formando uma estrutura compacta e produtiva.', 'Com o giro lento, cada prateleira passa pela água com nutrientes e depois volta à luz. O mesmo movimento também traz os vasos para perto, facilitando observar, cuidar e colher.'], quote: 'Verde que gira, vida que cresce.' },
  en: { kicker: 'About HortiVita', title: 'A simple idea that grew within a family.', lead: 'HortiVita was created to make growing easier in small spaces and reconnect people with the source of their food.', section: 'Our origin', headline: 'Growing well can also be practical.', body: 'The project brings together hands-on experience, creativity and agronomy. The solution was built and improved as a family, always with a clear goal: use space wisely, keep plants close and make everyday care more comfortable.', historyTitle: 'From a real need to a garden that turns.', history: ['The idea began with the search for a way to grow where there is no room for garden beds. Plants were arranged on shelves around a central axis, creating a compact and productive structure.', 'As it turns slowly, each shelf passes through the nutrient solution and then returns to the light. The same movement brings pots closer, making them easier to inspect, care for and harvest.'], quote: 'Green that turns, life that grows.' },
} as const;

export default function Sobre() {
  const [lang,setLang]=useState<'pt'|'en'>('pt'); const t=data[lang];
  return <main><SiteHeader solid lang={lang} onToggle={()=>setLang(lang==='pt'?'en':'pt')}/><section className="sub-hero sub-hero-split"><div><p className="eyebrow"><span/>{t.kicker}</p><h1>{t.title}</h1><p>{t.lead}</p></div><div className="sub-hero-media poster-media"><img src="/brand-post.webp" alt={lang==='pt'?'Publicação institucional da HortiVita':'HortiVita institutional post'}/></div></section><section className="about-intro"><div><p className="section-index">01 / {t.section}</p><h2>{t.headline}</h2></div><p>{t.body}</p></section><section className="history-grid"><div className="history-visual"><img src="/roots.webp" alt={lang==='pt'?'Raízes saudáveis de uma hortaliça':'Healthy roots of a leafy green'}/><span>DESIGN<br/>+ VIDA</span></div><div className="history-copy"><span className="big-index">02</span><h3>{t.historyTitle}</h3>{t.history.map(p=><p key={p}>{p}</p>)}</div></section><blockquote className="manifesto"><span>“</span><p>{t.quote}</p></blockquote><SiteFooter lang={lang}/></main>;
}
