'use client';

import { ArrowUpRight, Building2, CheckCircle2, Mail, MapPin, MessageCircle } from 'lucide-react';
import { useState } from 'react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';

const data = {
  pt: { kicker: 'Contato', title: 'Conte o que você quer cultivar.', lead: 'Fale sobre o espaço, o tipo de uso e as plantas que tem em mente. Essas informações ajudam a equipe a entender o seu projeto.', formTitle: 'Pedir informações ou orçamento', name: 'Nome', email: 'E-mail', phone: 'Telefone / WhatsApp', profile: 'Tipo de projeto', options: ['Residência', 'Escola', 'Restaurante', 'Empresa ou paisagismo', 'Outro'], message: 'Como é o espaço e o que você gostaria de cultivar?', submit: 'Enviar por e-mail', success: 'Abrimos uma mensagem no seu aplicativo de e-mail.', direct: 'Contato direto', directText: 'Se preferir, envie sua mensagem diretamente para o canal comercial.', rep: 'Projetos', region: 'Cada espaço é avaliado', regionText: 'A equipe conversa com você sobre instalação, iluminação, configuração e possíveis personalizações.', location: 'Atendimento sob consulta', response: 'Retorno assim que possível.' },
  en: { kicker: 'Contact', title: 'Tell us what you would like to grow.', lead: 'Share the space, intended use and plants you have in mind. This helps the team understand your project.', formTitle: 'Request information or a quote', name: 'Name', email: 'Email', phone: 'Phone / WhatsApp', profile: 'Project type', options: ['Home', 'School', 'Restaurant', 'Company or landscaping', 'Other'], message: 'What is the space like and what would you like to grow?', submit: 'Send by email', success: 'We opened a message in your email app.', direct: 'Direct contact', directText: 'If you prefer, send your message directly to the commercial contact.', rep: 'Projects', region: 'Each space is assessed', regionText: 'The team will discuss installation, lighting, setup and possible customizations with you.', location: 'Service by consultation', response: 'We will reply as soon as possible.' },
} as const;

export default function Contato() {
  const [lang,setLang]=useState<'pt'|'en'>('pt'); const [sent,setSent]=useState(false); const t=data[lang];
  function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f=new FormData(e.currentTarget); const value=(key:string)=>{const item=f.get(key); return typeof item==='string'?item:''}; const subject=encodeURIComponent(`HortiVita — ${value('perfil')}`); const body=encodeURIComponent(`Nome: ${value('nome')}\nE-mail: ${value('email')}\nTelefone: ${value('telefone')}\nProjeto: ${value('perfil')}\n\n${value('mensagem')}`); window.location.href=`mailto:contato@hortivita.com.br?subject=${subject}&body=${body}`; setSent(true); }
  return <main><SiteHeader solid lang={lang} onToggle={() => setLang(lang==='pt'?'en':'pt')}/>
    <section className="sub-hero contact-hero"><p className="eyebrow"><span/>{t.kicker}</p><h1>{t.title}</h1><p>{t.lead}</p></section>
    <section className="contact-layout"><form className="contact-form" onSubmit={submit}><p className="section-index">01 / {t.formTitle}</p><div className="field-row"><label>{t.name}<input name="nome" required/></label><label>{t.email}<input name="email" type="email" required/></label></div><div className="field-row"><label>{t.phone}<input name="telefone"/></label><label>{t.profile}<select name="perfil">{t.options.map(o=><option key={o}>{o}</option>)}</select></label></div><label>{t.message}<textarea name="mensagem" rows={5} required/></label><button className="button primary" type="submit">{t.submit}<ArrowUpRight size={18}/></button>{sent&&<p className="form-success"><CheckCircle2 size={17}/>{t.success}</p>}</form>
      <div className="contact-info"><article><Mail/><p className="section-index">02 / {t.direct}</p><h3>contato@hortivita.com.br</h3><p>{t.directText}</p><a href="mailto:contato@hortivita.com.br">{t.submit}<ArrowUpRight size={16}/></a></article><article><Building2/><p className="section-index">03 / {t.rep}</p><h3>{t.region}</h3><p>{t.regionText}</p><span><MapPin size={16}/>{t.location}</span><span><MessageCircle size={16}/>{t.response}</span></article></div>
    </section><SiteFooter lang={lang}/></main>;
}
