'use client';

import { ArrowRight, ArrowUpRight, Check } from 'lucide-react';
import { useState } from 'react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';

const data={
  pt:{kicker:'Soluções e configurações',title:'Onde você quer cultivar?',lead:'A HortiVita pode atender diferentes usos. A capacidade, as medidas e os itens de cada versão ainda são definidos com a equipe antes do orçamento.',note:'As opções abaixo mostram possibilidades de uso — não são fichas técnicas fechadas.',models:[['RESIDENCIAL','Para casa','Pensada para varandas, áreas gourmet, quintais e outros espaços compactos.',['Cultivo perto da cozinha','Hortaliças e temperos ao alcance','Luz complementar quando necessária']],['EDUCAÇÃO','Para escolas','Uma horta pedagógica para observar as plantas, registrar mudanças e aprender fazendo.',['Experiência visível e participativa','Apoio a atividades de ciência e alimentação','Uso com supervisão de adultos']],['COMERCIAL','Para negócios e projetos','Pode integrar restaurantes, empresas, instituições e projetos de paisagismo produtivo.',['Presença visual no ambiente','Cultivo próximo ao local de uso','Configuração avaliada para cada espaço']]],custom:'Conversar sobre esta opção',cta:'Precisa de uma configuração diferente?',ctaText:'Conte como é o seu espaço. A equipe pode avaliar tamanho, iluminação, instalação e acabamento antes de preparar a proposta.',button:'Falar com a equipe'},
  en:{kicker:'Solutions and setups',title:'Where would you like to grow?',lead:'HortiVita can serve different uses. Capacity, dimensions and included features are confirmed with the team before a quote is prepared.',note:'The options below show possible uses, not final technical specifications.',models:[['RESIDENTIAL','For home','Designed for balconies, entertainment areas, backyards and other compact spaces.',['Growing close to the kitchen','Greens and herbs within reach','Supplemental light when needed']],['EDUCATION','For schools','A learning garden where students can observe plants, record changes and learn by doing.',['Visible, hands-on experience','Support for science and food activities','Use with adult supervision']],['COMMERCIAL','For businesses and projects','Can be integrated into restaurants, companies, institutions and productive landscaping projects.',['A strong visual presence','Growing close to the point of use','A setup assessed for each space']]],custom:'Discuss this option',cta:'Need a different setup?',ctaText:'Tell us about your space. The team can assess size, lighting, installation and finish before preparing a proposal.',button:'Talk to the team'}
} as const;

export default function Modelos(){const[lang,setLang]=useState<'pt'|'en'>('pt');const t=data[lang];return <main><SiteHeader solid lang={lang} onToggle={()=>setLang(lang==='pt'?'en':'pt')}/><section className="sub-hero"><p className="eyebrow"><span/>{t.kicker}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="models-section standalone"><div className="section-heading"><p className="section-index">01 / {t.kicker}</p><h2>{t.title}</h2><p>{t.note}</p></div><div className="model-grid">{t.models.map(([label,title,text,items],i)=><article className={i===1?'featured':''} key={title}><div className="model-top"><span>{label}</span><b>0{i+1}</b></div><h3>{title}</h3><p>{text}</p><ul>{items.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><a href="/contato">{t.custom}<ArrowRight size={17}/></a></article>)}</div></section><section className="closing-cta compact"><p>{t.cta}</p><div><span>{t.ctaText}</span><a href="/contato">{t.button}<ArrowUpRight/></a></div></section><SiteFooter lang={lang}/></main>}
