'use client';

import { ArrowRight, ArrowUpRight, Check } from 'lucide-react';
import { useState } from 'react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';

const data={
  pt:{kicker:'Modelos e configurações',title:'Uma HortiVita para cada ambiente.',lead:'A estrutura, a capacidade e os acabamentos podem ser adaptados ao espaço e ao objetivo de cada projeto.',note:'Capacidades e dimensões finais são definidas conforme o projeto.',models:[['CASA','HortiVita Casa','Para varandas, cozinhas, áreas gourmet e ambientes internos.',['Estrutura compacta','Cultivo para consumo próprio','Iluminação opcional']],['EDUCAÇÃO','HortiVita Educa','Uma plataforma viva para escolas, oficinas e projetos de ciência.',['Configuração didática','Acesso facilitado aos alunos','Apoio a projetos pedagógicos']],['PRO','HortiVita Pro','Para restaurantes, empresas e projetos paisagísticos de impacto.',['Capacidade ampliada','Acabamentos personalizados','Integração ao ambiente']]],custom:'Personalizar projeto',cta:'Ainda não encontrou a configuração ideal?',ctaText:'Podemos desenvolver uma HortiVita sob medida para as necessidades do seu ambiente.',button:'Falar com a equipe'},
  en:{kicker:'Models and configurations',title:'A HortiVita for every environment.',lead:'Structure, capacity and finishes can be adapted to the space and purpose of each project.',note:'Final capacities and dimensions are defined for each project.',models:[['HOME','HortiVita Home','For balconies, kitchens, entertainment areas and indoor spaces.',['Compact structure','Growing for personal use','Optional lighting']],['EDUCATION','HortiVita Edu','A living platform for schools, workshops and science projects.',['Learning-oriented setup','Easy access for students','Support for school projects']],['PRO','HortiVita Pro','For restaurants, companies and high-impact landscape projects.',['Expanded capacity','Custom finishes','Integration with the space']]],custom:'Customize project',cta:'Still looking for the ideal configuration?',ctaText:'We can develop a HortiVita tailored to the needs of your environment.',button:'Talk to our team'}
} as const;

export default function Modelos(){const[lang,setLang]=useState<'pt'|'en'>('pt');const t=data[lang];return <main><SiteHeader solid lang={lang} onToggle={()=>setLang(lang==='pt'?'en':'pt')}/><section className="sub-hero"><p className="eyebrow"><span/>{t.kicker}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="models-section standalone"><div className="section-heading"><p className="section-index">01 / {t.kicker}</p><h2>{t.title}</h2><p>{t.note}</p></div><div className="model-grid">{t.models.map(([label,title,text,items],i)=><article className={i===1?'featured':''} key={title}><div className="model-top"><span>{label}</span><b>0{i+1}</b></div><h3>{title}</h3><p>{text}</p><ul>{items.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul><a href="/contato">{t.custom}<ArrowRight size={17}/></a></article>)}</div></section><section className="closing-cta compact"><p>{t.cta}</p><div><span>{t.ctaText}</span><a href="/contato">{t.button}<ArrowUpRight/></a></div></section><SiteFooter lang={lang}/></main>}
