'use client';

import { Check, Droplets, Leaf, Lightbulb, RotateCw } from 'lucide-react';
import { useState } from 'react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';
import { sitePath } from '@/lib/site-path';

const data = {
  pt: { kicker: 'Como funciona', title: 'A máquina gira. A água fica no ciclo.', lead: 'As prateleiras alternam o contato com a solução nutritiva e a exposição à luz. É um ciclo fácil de entender e acompanhar.', steps: [['01','Plante','As mudas ficam em recipientes com substrato, organizados nas prateleiras ao redor do eixo central.'],['02','Gire','A estrutura gira devagar e leva cada prateleira por diferentes posições da máquina.'],['03','Nutra','Na parte de baixo, o substrato absorve água e nutrientes por capilaridade. A solução permanece na base para ser reaproveitada.'],['04','Volte à luz','Depois da irrigação, as plantas retornam à luz natural. Em ambientes internos, pode ser usada iluminação complementar.']], components: 'O que forma o sistema', list: ['Estrutura vertical com prateleiras giratórias','Recipientes com substrato para as plantas','Bandeja ou reservatório na base','Água com nutrientes reaproveitada no ciclo','Iluminação complementar como opção'], alt: 'Detalhe dos potes e da base de irrigação da HortiVita' },
  en: { kicker: 'How it works', title: 'The machine turns. Water stays in the cycle.', lead: 'Shelves alternate between the nutrient solution and the light. It is a cycle that is easy to see and follow.', steps: [['01','Plant','Seedlings sit in containers with substrate, arranged on shelves around the central axis.'],['02','Turn','The structure turns slowly and carries each shelf through different positions.'],['03','Feed','At the bottom, the substrate absorbs water and nutrients by capillary action. The solution stays at the base for reuse.'],['04','Return to light','After watering, plants return to natural light. Supplemental lighting may be used indoors.']], components: 'What makes up the system', list: ['Vertical frame with rotating shelves','Plant containers with substrate','Tray or reservoir at the base','Nutrient solution reused in the cycle','Optional supplemental lighting'], alt: 'Detail of HortiVita pots and irrigation base' },
} as const;
const icons=[Leaf,RotateCw,Lightbulb,Droplets];

export default function ComoFunciona(){const[lang,setLang]=useState<'pt'|'en'>('pt');const t=data[lang];return <main><SiteHeader solid lang={lang} onToggle={()=>setLang(lang==='pt'?'en':'pt')}/><section className="sub-hero sub-hero-split"><div><p className="eyebrow"><span/>{t.kicker}</p><h1>{t.title}</h1><p>{t.lead}</p></div><div className="sub-hero-media"><img src={sitePath('/product-installation.webp')} alt={lang==='pt'?'Estrutura, prateleiras e reservatório da HortiVita':'HortiVita frame, shelves and reservoir'}/></div></section><section className="how-section standalone"><div className="steps">{t.steps.map(([n,title,text],i)=>{const Icon=icons[i];return <article key={n}><div className="step-top"><span>{n}</span><Icon/></div><h3>{title}</h3><p>{text}</p></article>})}</div><div className="components-panel"><div className="component-image"><img src={sitePath('/detail.webp')} alt={t.alt}/></div><div><p className="section-index">02 / {t.components}</p><h3>{t.components}</h3><ul>{t.list.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul></div></div></section><SiteFooter lang={lang}/></main>}
