'use client';

import { Check, Droplets, Leaf, Lightbulb, RotateCw } from 'lucide-react';
import { useState } from 'react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';

const data = {
  pt: { kicker: 'Como funciona', title: 'Um ciclo simples, preciso e contínuo.', lead: 'Movimento, água e luz trabalham juntos para manter cada planta acessível e bem cuidada.', steps: [['01','Cultive','As mudas crescem em potes individuais, com raízes nutridas diretamente pela solução hidropônica.'],['02','Rotacione','As prateleiras se movimentam ao longo do tempo, levando as plantas ao ponto de irrigação e alternando a exposição luminosa.'],['03','Ilumine','Em ambientes fechados, a iluminação artificial complementa ou substitui a luz solar conforme a necessidade.'],['04','Colha','A altura e o movimento do sistema mantêm as hortaliças ao alcance, facilitando o cuidado diário.']], components: 'Componentes integrados', list: ['Estrutura rotativa e prateleiras','Potes de cultivo individuais','Reservatório e circuito de irrigação','Controle de movimento e temporização','Iluminação suplementar opcional'], alt: 'Detalhe dos potes e da irrigação da HortiVita' },
  en: { kicker: 'How it works', title: 'A simple, precise and continuous cycle.', lead: 'Movement, water and light work together to keep every plant accessible and well cared for.', steps: [['01','Grow','Seedlings grow in individual pots, their roots fed directly by the hydroponic nutrient solution.'],['02','Rotate','Shelves move over time, carrying plants to the irrigation point and alternating their light exposure.'],['03','Light','Indoors, artificial lighting complements or replaces sunlight according to plant needs.'],['04','Harvest','The system height and movement keep greens within reach, making daily care comfortable.']], components: 'Integrated components', list: ['Rotating frame and shelves','Individual growing pots','Reservoir and irrigation circuit','Motion and timing control','Optional supplemental lighting'], alt: 'Detail of HortiVita pots and irrigation system' },
} as const;
const icons=[Leaf,RotateCw,Lightbulb,Droplets];

export default function ComoFunciona(){const[lang,setLang]=useState<'pt'|'en'>('pt');const t=data[lang];return <main><SiteHeader solid lang={lang} onToggle={()=>setLang(lang==='pt'?'en':'pt')}/><section className="sub-hero"><p className="eyebrow"><span/>{t.kicker}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="how-section standalone"><div className="steps">{t.steps.map(([n,title,text],i)=>{const Icon=icons[i];return <article key={n}><div className="step-top"><span>{n}</span><Icon/></div><h3>{title}</h3><p>{text}</p></article>})}</div><div className="components-panel"><div className="component-image"><img src="/detail.webp" alt={t.alt}/></div><div><p className="section-index">02 / {t.components}</p><h3>{t.components}</h3><ul>{t.list.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul></div></div></section><SiteFooter lang={lang}/></main>}
