'use client';

import { ArrowUpRight, GraduationCap, House, Utensils } from 'lucide-react';
import { useState } from 'react';
import { SiteFooter } from '@/components/site-footer';
import { SiteHeader } from '@/components/site-header';
import { sitePath } from '@/lib/site-path';

const data={
  pt:{kicker:'Projetos',title:'A HortiVita em espaços reais.',lead:'Na escola, no restaurante ou em casa, a máquina ganha um papel diferente — ensinar, compor o ambiente ou produzir perto da cozinha.',schoolKicker:'Projeto em destaque',schoolTitle:'Cultivando o Futuro',schoolText:'A EMEI Amor e Carinho, em Cotiporã (RS), recebeu a HortiVita como horta pedagógica. As crianças podem acompanhar o crescimento das plantas e conversar sobre alimentação, água e cuidado com o meio ambiente.',schoolDetail:'O projeto teve apoio do Fundo Social Sicredi Serrana RS 2026/1, da escola, do Município de Cotiporã e da comunidade escolar. A proposta inclui instalação, capacitação dos professores e materiais educativos.',schoolLink:'Ver publicação da escola',credit:'Imagem e informações: Município de Cotiporã (RS)',projects:[['Escola','Aprender cuidando','Na EMEI Amor e Carinho, a horta giratória virou uma ferramenta para observar, registrar e aprender todos os dias.'],['Restaurante','Verde que faz parte do espaço','No restaurante, a HortiVita pode unir paisagismo e cultivo de temperos e hortaliças perto do local de uso.'],['Residência','Alimento mais perto de casa','Em uma residência, ajuda a produzir hortaliças e temperos com acesso confortável e cuidado organizado.']],section:'Outros usos'},
  en:{kicker:'Projects',title:'HortiVita in real spaces.',lead:'At school, in a restaurant or at home, the machine plays a different role: teaching, shaping the space or growing close to the kitchen.',schoolKicker:'Featured project',schoolTitle:'Growing the Future',schoolText:'EMEI Amor e Carinho, in Cotiporã, Rio Grande do Sul, received HortiVita as a learning garden. Children can follow plant growth and talk about food, water and caring for the environment.',schoolDetail:'The project was supported by Fundo Social Sicredi Serrana RS 2026/1, the school, the Municipality of Cotiporã and the school community. It includes installation, teacher training and educational materials.',schoolLink:'View the school post',credit:'Image and information: Municipality of Cotiporã, RS',projects:[['School','Learning through care','At EMEI Amor e Carinho, the rotating garden became a tool for daily observation, recording and learning.'],['Restaurant','Greenery that belongs in the space','In a restaurant, HortiVita can combine landscaping with herbs and greens grown close to where they are used.'],['Home','Food grown closer to home','At home, it supports growing greens and herbs with comfortable access and organized care.']],section:'Other uses'}
} as const;
const icons=[GraduationCap,Utensils,House];

export default function Projetos(){const[lang,setLang]=useState<'pt'|'en'>('pt');const t=data[lang];return <main><SiteHeader solid lang={lang} onToggle={()=>setLang(lang==='pt'?'en':'pt')}/><section className="sub-hero"><p className="eyebrow"><span/>{t.kicker}</p><h1>{t.title}</h1><p>{t.lead}</p></section><section className="school-feature"><div className="school-image"><img src={sitePath('/school-project.webp')} alt={lang==='pt'?'Projeto Cultivando o Futuro na EMEI Amor e Carinho':'Growing the Future project at EMEI Amor e Carinho'}/><small>{t.credit}</small></div><div><p className="section-index">01 / {t.schoolKicker}</p><h2>{t.schoolTitle}</h2><p>{t.schoolText}</p><p>{t.schoolDetail}</p><a href="https://www.instagram.com/p/DcJSQllFvkR/?img_index=1" target="_blank" rel="noreferrer">{t.schoolLink}<ArrowUpRight size={18}/></a></div></section><section className="projects-section standalone"><div className="section-heading"><p className="section-index">02 / {t.section}</p><h2>{t.title}</h2></div><div className="project-grid">{t.projects.map(([label,title,text],i)=>{const Icon=icons[i];return <article key={label}><div><Icon/><span>{label}</span></div><h3>{title}</h3><p>{text}</p><span className="project-no">0{i+1}</span></article>})}</div></section><SiteFooter lang={lang}/></main>}
